name: Trigger auto deployment for ragvaleotest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ragvaleotest-AutoDeployTrigger-99f0e858-8cf6-48b1-b2f1-0c31226bef2b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RAGVALEOTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RAGVALEOTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RAGVALEOTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.RAGVALEOTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RAGVALEOTEST_REGISTRY_PASSWORD }}
          containerAppName: ragvaleotest
          resourceGroup: first_project_spark_sg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


